-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 13:32:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 01_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 01_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `01_bd` DEFAULT CHARACTER SET utf8 ;
USE `01_bd` ;

-- -----------------------------------------------------
-- Table `01_bd`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_bd`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_bd`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_bd`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_bd`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_bd`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `categoria` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_categorias1_idx` (`categoria` ASC)  ,
  CONSTRAINT `fk_produtos_categorias1`
    FOREIGN KEY (`categoria`)
    REFERENCES `01_bd`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_bd`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_bd`.`vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATE NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendas_clientes1_idx` (`cliente` ASC)  ,
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`cliente`)
    REFERENCES `01_bd`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_bd`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_bd`.`itens` (
  `venda` INT NOT NULL,
  `produto` INT NOT NULL,
  `qtd` INT NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`venda`, `produto`),
  INDEX `fk_vendas_has_produtos_produtos1_idx` (`produto` ASC)  ,
  INDEX `fk_vendas_has_produtos_vendas1_idx` (`venda` ASC)  ,
  CONSTRAINT `fk_vendas_has_produtos_vendas1`
    FOREIGN KEY (`venda`)
    REFERENCES `01_bd`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_has_produtos_produtos1`
    FOREIGN KEY (`produto`)
    REFERENCES `01_bd`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_bd`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_bd`.`login` (
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `clientes_id` INT NOT NULL,
  INDEX `fk_login_clientes1_idx` (`clientes_id` ASC)  ,
  CONSTRAINT `fk_login_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `01_bd`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
